services:
   synapse:
    image: ghcr.io/element-hq/synapse
    #image: matrixdotorg/synapse:latest
    hostname: synapse
    container_name: synapse
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
      UID: 
      GID: 
      TZ: 
    volumes:
      - ${APP_PATH}matrix/synapse:/data
    
    depends_on:
    - db
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
      - "traefik.http.routers.synapse.rule=Host(`synapse.${DOMAINN}`)"
      - "traefik.http.routers.synapse.entrypoints=https"
      - "traefik.http.routers.synapse.tls.certresolver=le"
