services:
  db:
    image: registry.gitlab.com/coolpub/postgres17
    container_name: postgress
    hostname: postgres
    restart: unless-stopped

    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    
    secrets:
      - postgres_password
    
    #ports:
      #- mode: host
        #target: 5432
        #published: 5432
        #protocol: tcp
    networks:
     - proxy

    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C

    healthcheck:
        test: pg_isready
        interval: 60s
        retries: 3
        start_period: 10s
        timeout: 10s

    volumes:
      - postgres17_data:/var/lib/postgresql/data
      - ${SEC_PATH}/postgres:/docker-entrypoint-initdb.d

secrets:
  postgres_password:
    file: ${SEC_PATH}postgres_password
