services:
 ntfy:
  container_name: ntfy
  command:
  - serve

  hostname: ntfy-server
  image: binwiederhier/ntfy
  networks:
      proxy:

  restart: unless-stopped

  environment:
      NTFY_BASE_URL: https://ntfy.${DOMAINN}
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_LOG_DIR: /var/log/ntfy
      NTFY_ENABLE_LOGIN: true
      TZ: America/New_York



  volumes:
      - ntfy-data:/var/lib/ntfy
      - ${APP_PATH}ntfy:/etc/ntfy


  #labels:
  #    - "traefik.enable=true"
  ##    - "traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAINN}`)"
   #   - "traefik.http.services.ntfy.loadbalancer.server.port=80"

  labels:
      - "traefik.enable=true"
    ## HTTP Routers
      - "traefik.http.routers.ntfy-rtr.rule=Host(`ntfy.${DOMAINN}`)"
      - "traefik.http.routers.ntfy-rtr.entrypoints=https"
      - "traefik.http.routers.ntfy-rtr.tls=true"    
#      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
      - "traefik.http.middlewares.compresstraefik.compress=true"