services:
  db2:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped

    #command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    
    secrets:
      - postgres_password
    
    #ports:
      #- mode: host
        #target: 5432
        #published: 5432
        #protocol: tcp
    networks:
     - proxy

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/postgres_password
      TZ:

    healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        interval: 10s
        retries: 3
        start_period: 10s
        timeout: 5s

    volumes:
      - mysql_data:/var/lib/mysql
      - ${SEC_PATH}/mysql:/docker-entrypoint-initdb.d

secrets:
  postgres_password:
    file: ${SEC_PATH}postgres_password
