services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    hostname: freshrss
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${APP_PATH}freshrss:/config
    networks:
     #- socket
     - proxy

    #ports:
    #  - 80:80
    restart: unless-stopped

    labels:
    - "traefik.http.routers.freshrss.rule=Host(`freshrss.${DOMAINN}`)"
    - "traefik.http.services.freshrss.loadbalancer.server.port=80"
    - "traefik.http.routers.freshrss.entrypoints=https"
    - "traefik.http.routers.freshrss.tls=true"
    - "traefik.http.routers.freshrss.tls.certresolver=le"